openapi: 3.0.0
info:
  title: Get Application Password KeyIds
  description: Retrieves password credential keyIds from an Azure AD application
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph API
paths:
  /applications/{applicationObjectId}:
    get:
      summary: Get password credentials keyIds
      description: Retrieves the passwordCredentials and keyCredentials arrays containing keyId values for a given application object
      operationId: getApplicationPasswordKeyIds
      parameters:
        - name: applicationObjectId
          in: path
          required: true
          description: The object ID of the application (not the clientId/appId)
          schema:
            type: string
        - name: $select
          in: query
          required: true
          description: Select specific properties to return
          schema:
            type: string
            default: passwordCredentials,keyCredentials
      responses:
        '200':
          description: Successfully retrieved application credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  passwordCredentials:
                    type: array
                    items:
                      type: object
                      properties:
                        keyId:
                          type: string
                          format: uuid
                        displayName:
                          type: string
                        endDateTime:
                          type: string
                          format: date-time
                  keyCredentials:
                    type: array
                    items:
                      type: object
                      properties:
                        keyId:
                          type: string
                          format: uuid
                        displayName:
                          type: string
                        endDateTime:
                          type: string
                          format: date-time
        '404':
          description: Application not found
