openapi: 3.0.0
info:
  title: Remove Service Principal Password
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /servicePrincipals/{servicePrincipal-id}/removePassword:
    post:
      summary: Remove a password credential from a service principal
      operationId: removeServicePrincipalPassword
      parameters:
        - in: path
          name: servicePrincipal-id
          schema:
            type: string
          required: true
          description: The ID of the service principal
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                keyId:
                  type: string
                  description: The ID (GUID) of the password credential to remove
              required:
                - keyId
        required: true
      responses:
        '204':
          description: No Content (success)
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Error
